name: Crowdin Action

on:
  # Uncomment to run on every push to master, this is recommended but turned off by default, in case you haven't set up your Crowdin project yet
  # push:
  #   branches: [master]
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_translations: true
          download_translations: true
          auto_approve_imported: true
          create_pull_request: true
          skip_untranslated_strings: true
          crowdin_branch_name: 'BRANCH_IN_CROWDIN'
          commit_message: 'i18n: update crowdin translations'
        env:
          # Add these secrets to your repository's secrets
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
